import Head from "next/head";
import Link from "next/link";
import { Button } from "@/components/mui";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";

export default function Custom404() {
  return (
    <>
      <Head>
        <title>Page not found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h1" variant="h3">
          Page Not Found
        </Heading>
        <Button href="/" component={Link}>
          Back to home page
        </Button>
      </Layout>
    </>
  );
}