import Head from "next/head";
import Image from "next/image";
// import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import ContactForm from "@/components/forms/ContactForm";
import { sendEmail } from "@/lib/api-functions/client";

// const inter = Inter({ subsets: ["latin"] });

export default function Contact() {
  return (
    <>
      <Head>
        <title>Shop Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Contact Us</Heading>
        <ContactForm submitHandler={sendEmail}/>
      </Layout>
    </>
  );
}
