import Head from "next/head";
import { useRouter } from "next/navigation";

import Layout from "@/components/Layout";
import Heading from "@/components/Heading";

import OrderForm from "@/components/forms/OrderForm";
import { useUpdate } from "@/lib/tq/orders/mutations";

import { fetchOrder } from "@/lib/api-functions/server/orders/queries";

export default function UpdateOrder({ ssd }) {
  const router = useRouter();
  const updateMutation = useUpdate();

  const submitHandler = (data) => {
    updateMutation.mutate(data);
    router.push("/admin/Orders/");
  };
  return (
    <>
      <Head>
        <title>Admin: Update Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2">Amend Order</Heading>
        <OrderForm
          Order={ssd}
          submitHandler={submitHandler}
        />
      </Layout>
    </>
  );
}

//calculated at the time it is called
export async function getServerSideProps({params}) {
  const Order = await fetchOrder(params.id).catch((err) => console.log(err));
  console.log("Order", Order);
  return { props: { ssd: JSON.parse(JSON.stringify(Order)) } };
}
